/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CrowdRouteImport } from './routes/crowd'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as VisitorRouteImport } from './routes/visitor'
import { Route as QueuesIndexRouteImport } from './routes/queues.index'
import { Route as QueuesQueueIdRouteImport } from './routes/queues.$queueId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CrowdRoute = CrowdRouteImport.update({
  id: '/crowd',
  path: '/crowd',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorRoute = VisitorRouteImport.update({
  id: '/visitor',
  path: '/visitor',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesIndexRoute = QueuesIndexRouteImport.update({
  id: '/queues/',
  path: '/queues/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesQueueIdRoute = QueuesQueueIdRouteImport.update({
  id: '/queues/$queueId',
  path: '/queues/$queueId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/crowd': typeof CrowdRoute
  '/dashboard': typeof DashboardRoute
  '/staff': typeof StaffRoute
  '/visitor': typeof VisitorRoute
  '/queues/$queueId': typeof QueuesQueueIdRoute
  '/queues/': typeof QueuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/crowd': typeof CrowdRoute
  '/dashboard': typeof DashboardRoute
  '/staff': typeof StaffRoute
  '/visitor': typeof VisitorRoute
  '/queues/$queueId': typeof QueuesQueueIdRoute
  '/queues': typeof QueuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/crowd': typeof CrowdRoute
  '/dashboard': typeof DashboardRoute
  '/staff': typeof StaffRoute
  '/visitor': typeof VisitorRoute
  '/queues/$queueId': typeof QueuesQueueIdRoute
  '/queues/': typeof QueuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/crowd'
    | '/dashboard'
    | '/staff'
    | '/visitor'
    | '/queues/$queueId'
    | '/queues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/crowd'
    | '/dashboard'
    | '/staff'
    | '/visitor'
    | '/queues/$queueId'
    | '/queues'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/crowd'
    | '/dashboard'
    | '/staff'
    | '/visitor'
    | '/queues/$queueId'
    | '/queues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CrowdRoute: typeof CrowdRoute
  DashboardRoute: typeof DashboardRoute
  StaffRoute: typeof StaffRoute
  VisitorRoute: typeof VisitorRoute
  QueuesQueueIdRoute: typeof QueuesQueueIdRoute
  QueuesIndexRoute: typeof QueuesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crowd': {
      id: '/crowd'
      path: '/crowd'
      fullPath: '/crowd'
      preLoaderRoute: typeof CrowdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitor': {
      id: '/visitor'
      path: '/visitor'
      fullPath: '/visitor'
      preLoaderRoute: typeof VisitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues/': {
      id: '/queues/'
      path: '/queues'
      fullPath: '/queues/'
      preLoaderRoute: typeof QueuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues/$queueId': {
      id: '/queues/$queueId'
      path: '/queues/$queueId'
      fullPath: '/queues/$queueId'
      preLoaderRoute: typeof QueuesQueueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  CrowdRoute: CrowdRoute,
  DashboardRoute: DashboardRoute,
  StaffRoute: StaffRoute,
  VisitorRoute: VisitorRoute,
  QueuesQueueIdRoute: QueuesQueueIdRoute,
  QueuesIndexRoute: QueuesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
