spring:
  application:
    name: backend
  data:
    mongodb:
      uri: mongodb+srv://sanskritisingh3287_db_user:EhOQCcf4RSPMyHRp@cluster0.wjqyarj.mongodb.net/byteforge?retryWrites=true&w=majority&appName=Cluster0
